[package]
name = "moosicbox_app"
version = "0.1.0"
description = "MoosicBox Tauri App"
authors = ["Braden Steffaniak"]
license = ""
repository = ""
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "moosicbox_lib"

[profile.release]
codegen-units = 1
lto = false
opt-level = 3
strip = "symbols"

[profile.debug-release]
debug = true
inherits = "release"
strip = "none"

[profile.release-lto]
inherits = "release"
lto = "fat"

[profile.release-lto-no-panic]
inherits = "release-lto"
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.0.0-beta.10", features = [] }

[dependencies]
moosicbox_core = { path = "../../MoosicBoxServer/packages/core", default-features = false }
moosicbox_env_utils = { path = "../../MoosicBoxServer/packages/env_utils", default-features = false }
moosicbox_player = { path = "../../MoosicBoxServer/packages/player", default-features = false }

free_log_client = { git = "https://github.com/BSteffaniak/FreeLog.git" }
tauri = { version = "2.0.0-beta.13", features = ["protocol-asset"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11.27", default-features = false, features = [
  "rustls-tls",
] }
portpicker = "0.1"
log = "0.4.21"
once_cell = { version = "1.19.0" }
debounce = "0.2.2"
atomic_float = "0.1.0"
strum = "0.26.2"
strum_macros = "0.26.2"
ndk-context = { version = "0.1.1", optional = true }
jni = { version = "0.21.1", optional = true }

[features]
default = ["cpal", "aac", "mp3", "opus"]

# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

android = ["dep:ndk-context", "dep:jni"]

# Player audio outputs
cpal = ["moosicbox_player/cpal", "moosicbox_player/oboe-shared-stdcxx"]
aac = ["moosicbox_core/aac"]
mp3 = ["moosicbox_core/mp3"]
opus = ["moosicbox_core/opus"]
jack = ["moosicbox_player/jack"]
asio = ["moosicbox_player/asio"]
pulseaudio = ["moosicbox_player/pulseaudio"]
pulseaudio-standard = ["moosicbox_player/pulseaudio-standard"]
pulseaudio-simple = ["moosicbox_player/pulseaudio-simple"]
