[package]
name = "moosicbox_app"
version = "0.1.0"
description = "MoosicBox Tauri App"
authors = ["Braden Steffaniak"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.11.20"
portpicker = "0.1"
moosicbox_core = { path = "../../MoosicBoxServer/packages/core" }
moosicbox_player = { path = "../../MoosicBoxServer/packages/player", default-features = false, features = [
  "opus",
] }
log = "0.4.20"
once_cell = { version = "1.18.0" }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-aptabase = { version = "0.4", optional = true }
debounce = "0.2.2"
atomic_float = "0.1.0"

[features]
default = ["cpal"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

# Player audio outputs
cpal = ["moosicbox_player/cpal"]
jack = ["moosicbox_player/jack"]
asio = ["moosicbox_player/asio"]
pulseaudio = ["moosicbox_player/pulseaudio"]
pulseaudio-standard = ["moosicbox_player/pulseaudio-standard"]
pulseaudio-simple = ["moosicbox_player/pulseaudio-simple"]

aptabase = ["dep:tauri-plugin-aptabase"]
