[package]
name = "moosicbox_app"
version = "0.1.0"
description = "MoosicBox Tauri App"
authors = ["Braden Steffaniak"]
license = ""
repository = ""
edition = "2021"

[profile.release]
codegen-units = 1
lto = false
opt-level = 3
panic = "abort"
strip = "symbols"

[profile.release-lto]
inherits = "release"
codegen-units = 1
lto = "fat"
opt-level = 3
panic = "abort"
strip = "symbols"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
moosicbox_core = { path = "../../MoosicBoxServer/packages/core", default-features = false }
moosicbox_player = { path = "../../MoosicBoxServer/packages/player", default-features = false }

tauri = { version = "1.5", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = "0.11.23"
portpicker = "0.1"
log = "0.4.20"
once_cell = { version = "1.19.0" }
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-aptabase = { version = "0.4", optional = true }
debounce = "0.2.2"
atomic_float = "0.1.0"
strum = "0.25.0"
strum_macros = "0.25.3"

[features]
default = ["cpal", "aac", "mp3", "opus"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

# Player audio outputs
cpal = ["moosicbox_player/cpal"]
aac = ["moosicbox_player/aac", "moosicbox_core/aac"]
mp3 = ["moosicbox_player/mp3", "moosicbox_core/mp3"]
opus = ["moosicbox_player/opus", "moosicbox_core/opus"]
jack = ["moosicbox_player/jack"]
asio = ["moosicbox_player/asio"]
pulseaudio = ["moosicbox_player/pulseaudio"]
pulseaudio-standard = ["moosicbox_player/pulseaudio-standard"]
pulseaudio-simple = ["moosicbox_player/pulseaudio-simple"]

aptabase = ["dep:tauri-plugin-aptabase"]
