[package]
authors     = ["Braden Steffaniak"]
categories  = ["network-programming"]
description = "MoosicBoxApp ws package"
edition     = "2021"
keywords    = ["websocket"]
license     = "MPL-2.0"
name        = "moosicbox_app_ws"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../../../MoosicBoxServer/packages/assert", default-features = false }
moosicbox_env_utils = { path = "../../../MoosicBoxServer/packages/env_utils", default-features = false }
moosicbox_files = { path = "../../../MoosicBoxServer/packages/files", default-features = false, features = [
    "range",
] }
moosicbox_task = { path = "../../../MoosicBoxServer/packages/task", default-features = false }

async-trait       = { workspace = true }
bytes             = { workspace = true }
futures-channel   = { workspace = true }
futures-util      = { workspace = true }
log               = { workspace = true }
rand              = { workspace = true }
regex             = { workspace = true }
reqwest           = { workspace = true }
serde             = { workspace = true, features = ["derive"] }
serde-aux         = { workspace = true }
serde_json        = { workspace = true }
thiserror         = { workspace = true }
tokio             = { workspace = true, features = ["tracing"] }
tokio-tungstenite = { workspace = true }
tokio-util        = { workspace = true }

[features]
default = []

fail-on-warnings = []
