[package]
authors     = ["Braden Steffaniak"]
categories  = []
description = "MoosicBoxApp bundled package"
edition     = "2021"
keywords    = ["bundled"]
license     = "MPL-2.0"
name        = "moosicbox_app_bundled"
readme      = "README.md"
repository  = "https://github.com/MoosicBox/MoosicBoxServer"
version     = "0.1.0"

[dependencies]
moosicbox_assert = { path = "../../../MoosicBoxServer/packages/assert", default-features = false }
moosicbox_async_service = { path = "../../../MoosicBoxServer/packages/async_service", default-features = false }
moosicbox_server = { path = "../../../MoosicBoxServer/packages/server", default-features = false, features = [
    "all-apis",
] }
moosicbox_task = { path = "../../../MoosicBoxServer/packages/task", default-features = false }

flume        = { workspace = true }
futures      = { workspace = true }
log          = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
tauri        = { workspace = true }
thiserror    = { workspace = true }
tokio        = { workspace = true }

[features]
default = []

fail-on-warnings = []

# Encoders
aac  = ["moosicbox_server/aac"]
flac = ["moosicbox_server/flac"]
mp3  = ["moosicbox_server/mp3"]
