name: Build and Validate UI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v4
              with:
                  path: MoosicBoxApp

            - name: Checkout MoosicBoxUI
              uses: actions/checkout@v4
              with:
                  repository: MoosicBox/MoosicBoxUI
                  path: MoosicBoxUI

            - name: Copy Files
              working-directory: MoosicBoxApp
              shell: bash
              run: |
                  ./copy-files.sh

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: ⚡ Cache pnpm
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ matrix.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-pnpm-store-

            - name: pnpm install
              working-directory: MoosicBoxApp
              run: pnpm install

            - name: pretty
              working-directory: MoosicBoxApp
              run: pnpm pretty

            - name: lint
              working-directory: MoosicBoxApp
              run: pnpm lint

            - name: typecheck
              working-directory: MoosicBoxApp
              run: pnpm typecheck
