name: Build and Validate UI

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - uses: actions/checkout@v4
              with:
                  path: MoosicBoxApp

            - name: Checkout MoosicBoxUI
              uses: actions/checkout@v4
              with:
                  repository: MoosicBox/MoosicBoxUI
                  path: MoosicBoxUI

            - uses: dtolnay/rust-toolchain@stable

            - name: ⚡ Cache cargo
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Build
              working-directory: MoosicBoxApp
              run: cargo build

            - name: Copy Files
              working-directory: MoosicBoxApp
              shell: bash
              run: |
                  ./copy-files.sh

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: pnpm install
              working-directory: MoosicBoxApp
              run: pnpm install

            - name: pretty
              working-directory: MoosicBoxApp
              run: pnpm pretty

            - name: lint
              working-directory: MoosicBoxApp
              run: pnpm lint

            - name: typecheck
              working-directory: MoosicBoxApp
              run: pnpm typecheck
