name: Create MoosicBoxApp Prerelease

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+*"
            - "*-nightly-*"
            - "master-[0-9a-f]+"

jobs:
    create-prerelease:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  path: MoosicBoxApp

            - name: Get latest stable release of MoosicBoxApp
              uses: rez0n/actions-github-release@main
              id: stable_release
              env:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository: "${{ github.repository }}"
                  type: "stable"

            - name: Get latest release of MoosicBoxApp
              uses: rez0n/actions-github-release@main
              id: latest_release
              env:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository: "${{ github.repository }}"
                  type: "latest"

            - uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}
                  tag: "${{github.ref_name}}"
                  prerelease: true
                  body: |
                      **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.stable_release.outputs.release || github.head_ref || github.ref_name }}...${{ github.ref_name }}
                      **Latest Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.latest_release.outputs.release }}...${{ github.ref_name }}
                  generateReleaseNotes: false
