name: Prepare MoosicBoxApp Release

on:
    release:
        types: [published, edited]

env:
    CARGO_TERM_COLOR: always

jobs:
    package:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout audiotags
              uses: actions/checkout@master
              with:
                  repository: BSteffaniak/audiotags
                  ref: feat/add-full-date-capabilities
                  path: audiotags

            - name: Checkout MoosicBoxServer
              uses: actions/checkout@master
              with:
                  repository: MoosicBox/MoosicBoxServer
                  path: MoosicBoxServer

            - uses: actions/checkout@v3
              with:
                  path: MoosicBoxApp

            - name: Get package version
              id: package_version
              working-directory: MoosicBoxApp/src-tauri
              shell: bash
              run: |
                  VERSION="$(cargo metadata --format-version=1 --no-deps | jq --raw-output '.packages[0].version')"
                  echo "version: $VERSION"
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Make assets directory test
              shell: bash
              id: assets_dir
              run: |
                  pwd
                  echo "${{ github.workspace }}"
                  mkdir assets2/
                  cd assets2
                  echo "path=$(pwd)" >> $GITHUB_OUTPUT

            - name: Make assets directory test2
              shell: bash
              run: |
                cp MoosicBoxApp/src/root.tsx "${{ steps.assets_dir.outputs.path }}/root.tsx"
                ls "${{ steps.assets_dir.outputs.path }}"

            - name: ⚡ Cache cargo
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install Dependencies
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: |
                  sudo apt update
                  sudo apt install libwebkit2gtk-4.0-dev \
                      build-essential \
                      curl \
                      wget \
                      file \
                      libssl-dev \
                      libgtk-3-dev \
                      libayatana-appindicator3-dev \
                      librsvg2-dev

            - name: Build
              working-directory: MoosicBoxApp/src-tauri
              run: cargo build --verbose

            - name: Checkout MoosicBoxUI
              uses: actions/checkout@master
              with:
                  repository: MoosicBox/MoosicBoxUI
                  path: MoosicBoxUI

            - name: Copy Files
              working-directory: MoosicBoxApp
              shell: bash
              run: |
                  ./copy-files.sh

            - uses: pnpm/action-setup@v2
              name: Install pnpm
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: ⚡ Cache pnpm
              uses: actions/cache@v3
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ matrix.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ matrix.os }}-pnpm-store-

            - name: pnpm install
              working-directory: MoosicBoxApp
              run: pnpm install

            - name: Build Tauri App
              working-directory: MoosicBoxApp
              run: pnpm tauri build

            - name: Make assets directory
              shell: bash
              run: mkdir ~/assets/

            - name: Add MoosicBox_amd64.deb Asset
              if: ${{ matrix.os == 'ubuntu-latest' }}
              working-directory: MoosicBoxApp/src-tauri/target/release/bundle
              run: |
                  mv deb/moosic-box_${{ steps.package_version.outputs.version }}_amd64.deb \
                      ~/assets/MoosicBox_amd64.deb

            - name: Add MoosicBox-amd64.AppImage Asset
              if: ${{ matrix.os == 'ubuntu-latest' }}
              working-directory: MoosicBoxApp/src-tauri/target/release/bundle
              run: |
                  mv appimage/moosic-box_${{ steps.package_version.outputs.version }}_amd64.AppImage \
                      ~/assets/MoosicBox-amd64.AppImage

            - name: Add MoosicBox_x64.app Asset
              if: ${{ matrix.os == 'macos-latest' }}
              shell: bash
              run: |
                  7z \
                      a \
                      -mx=9 \
                      -tzip \
                      ~/assets/MoosicBox_x64.app.zip \
                      MoosicBoxApp/src-tauri/target/release/bundle/macos/MoosicBox.app

            - name: Add MoosicBox_x64.dmg Asset
              if: ${{ matrix.os == 'macos-latest' }}
              working-directory: MoosicBoxApp/src-tauri/target/release/bundle
              run: |
                  mv dmg/MoosicBox_${{ steps.package_version.outputs.version }}_x64.dmg \
                      ~/assets/MoosicBox_x64.dmg

            - name: Add MoosicBox_x64-setup.exe Asset
              if: ${{ matrix.os == 'windows-latest' }}
              working-directory: MoosicBoxApp/src-tauri/target/release/bundle
              run: |
                  mv nsis/MoosicBox_${{ steps.package_version.outputs.version }}_x64-setup.exe \
                      ~/assets/MoosicBox_x64-setup.exe

            - name: Add MoosicBox_x64.exe Asset
              if: ${{ matrix.os == 'windows-latest' }}
              working-directory: MoosicBoxApp/src-tauri/target/release/bundle
              run: |
                  mv nsis/MoosicBox_${{ steps.package_version.outputs.version }}_x64_en-US.msi \
                      ~/assets/MoosicBox_x64_en-US.msi

            - name: Delete Linux Assets
              uses: mknejp/delete-release-assets@v1
              if: ${{ matrix.os == 'ubuntu-latest' }}
              with:
                  fail-if-no-assets: false
                  token: ${{ github.token }}
                  tag: ${{ github.event.release.tag_name }}
                  repository: ${{ github.repository }}
                  assets: |
                      MoosicBox_amd64.deb
                      MoosicBox-amd64.AppImage

            - name: Delete Mac Assets
              uses: mknejp/delete-release-assets@v1
              if: ${{ matrix.os == 'macos-latest' }}
              with:
                  fail-if-no-assets: false
                  token: ${{ github.token }}
                  tag: ${{ github.event.release.tag_name }}
                  repository: ${{ github.repository }}
                  assets: |
                      MoosicBox_x64.app.zip
                      MoosicBox_x64.dmg

            - name: Delete Windows Assets
              uses: mknejp/delete-release-assets@v1
              if: ${{ matrix.os == 'windows-latest' }}
              with:
                  fail-if-no-assets: false
                  token: ${{ github.token }}
                  tag: ${{ github.event.release.tag_name }}
                  repository: ${{ github.repository }}
                  assets: |
                      MoosicBox_x64-setup.exe
                      MoosicBox_x64.msi

            - name: Upload Assets
              uses: softprops/action-gh-release@v1
              with:
                  token: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}
                  files: ~/assets/*

    compress:
        runs-on: ubuntu-latest
        needs: package

        strategy:
            fail-fast: false
            matrix:
                compression:
                    - algorithm: xz
                      extension: xz
                      replace_extension: false
                      compression_level: 9
                      content_type: application/octet-stream
                    - algorithm: 7z
                      extension: 7z
                      replace_extension: true
                      compression_level: 9
                      content_type: application/octet-stream
                    - algorithm: bzip2
                      extension: bz2
                      replace_extension: false
                      compression_level: 9
                      content_type: application/octet-stream
                    - algorithm: gzip
                      extension: gz
                      replace_extension: false
                      compression_level: 9
                      content_type: application/x-gzip
                    - algorithm: zip
                      extension: zip
                      replace_extension: true
                      compression_level: 9
                      content_type: application/x-zip-compressed
                asset:
                    - name: MoosicBox_amd64
                      extension: deb
                      decompress: false
                    - name: MoosicBox_amd64
                      extension: AppImage
                      decompress: false
                    - name: MoosicBox_x64
                      extension: app
                      decompress: true
                      decompress_file: MoosicBox_x64.app.zip
                      decompress_algorithm: zip
                    - name: MoosicBox_x64
                      extension: dmg
                      decompress: false
                    - name: MoosicBox_x64-setup
                      extension: exe
                      decompress: false
                    - name: MoosicBox_x64
                      extension: msi
                      decompress: false

        steps:
            - name: Download ${{ matrix.asset }} Asset
              uses: dsaltares/fetch-gh-release-asset@master
              with:
                  repo: ${{ github.repository }}
                  file: ${{ matrix.asset }}
                  version: ${{ github.event.release.id }}

            - name: Decompress
              if: ${{ matrix.asset.decompress }}
              run: |
                  7z \
                      x \
                      -t${{ matrix.asset.decompress_algorithm }} \
                      ${{ matrix.asset.decompress_file }} \
                      -o${{ matrix.asset.name }}.${{ matrix.asset.extension }}

            - name: Compress ${{ matrix.asset }}
              run: |
                  7z \
                      a \
                      -mx=${{ matrix.compression.compression_level }} \
                      -t${{ matrix.compression.algorithm }} \
                      ${{ matrix.compression.replace_extension && '${{ matrix.asset.name }}' || '${{ matrix.asset.name }}${{ matrix.asset.extension }}' }}.${{ matrix.compression.extension }} \
                      ${{ matrix.asset.name }}.${{ matrix.asset.extension }}

            - name: Delete ${{ matrix.compression.replace_extension && '${{ matrix.asset.name }}' || '${{ matrix.asset.name }}${{ matrix.asset.extension }}' }}.${{ matrix.compression.extension }} Asset
              uses: mknejp/delete-release-assets@v1
              with:
                  fail-if-no-assets: false
                  token: ${{ github.token }}
                  tag: ${{ github.event.release.tag_name }}
                  repository: ${{ github.repository }}
                  assets: ${{ matrix.compression.replace_extension && '${{ matrix.asset.name }}' || '${{ matrix.asset.name }}${{ matrix.asset.extension }}' }}.${{ matrix.compression.extension }}

            - name: Upload Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.WORKFLOW_MANAGEMENT_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./${{ matrix.compression.replace_extension && '${{ matrix.asset.name }}' || '${{ matrix.asset.name }}${{ matrix.asset.extension }}' }}.${{ matrix.compression.extension }}
                  asset_name: ${{ matrix.compression.replace_extension && '${{ matrix.asset.name }}' || '${{ matrix.asset.name }}${{ matrix.asset.extension }}' }}.${{ matrix.compression.extension }}
                  asset_content_type: ${{ matrix.compression.content_type }}
